version: '3.5'

services:
  wordles:
    container_name: wordles
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    env_file:
      - ../.env
    restart: unless-stopped

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local


